[Wed Apr 24 15:01:27.394580 2019] [wsgi:error] [pid 11940] [remote 162.158.155.116:47952] [2019-04-24 15:01:27,394] ERROR in app: Exception on /modules/ [POST]
[Wed Apr 24 15:01:27.394630 2019] [wsgi:error] [pid 11940] [remote 162.158.155.116:47952] Traceback (most recent call last):
[Wed Apr 24 15:01:27.394636 2019] [wsgi:error] [pid 11940] [remote 162.158.155.116:47952]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
[Wed Apr 24 15:01:27.394640 2019] [wsgi:error] [pid 11940] [remote 162.158.155.116:47952]     response = self.full_dispatch_request()
[Wed Apr 24 15:01:27.394643 2019] [wsgi:error] [pid 11940] [remote 162.158.155.116:47952]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
[Wed Apr 24 15:01:27.394647 2019] [wsgi:error] [pid 11940] [remote 162.158.155.116:47952]     rv = self.handle_user_exception(e)
[Wed Apr 24 15:01:27.394650 2019] [wsgi:error] [pid 11940] [remote 162.158.155.116:47952]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
[Wed Apr 24 15:01:27.394654 2019] [wsgi:error] [pid 11940] [remote 162.158.155.116:47952]     reraise(exc_type, exc_value, tb)
[Wed Apr 24 15:01:27.394657 2019] [wsgi:error] [pid 11940] [remote 162.158.155.116:47952]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
[Wed Apr 24 15:01:27.394660 2019] [wsgi:error] [pid 11940] [remote 162.158.155.116:47952]     rv = self.dispatch_request()
[Wed Apr 24 15:01:27.394663 2019] [wsgi:error] [pid 11940] [remote 162.158.155.116:47952]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
[Wed Apr 24 15:01:27.394667 2019] [wsgi:error] [pid 11940] [remote 162.158.155.116:47952]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Apr 24 15:01:27.394670 2019] [wsgi:error] [pid 11940] [remote 162.158.155.116:47952]   File "/var/www/ExGen/ExGenApp/app/routes.py", line 35, in wrap
[Wed Apr 24 15:01:27.394673 2019] [wsgi:error] [pid 11940] [remote 162.158.155.116:47952]     return f(*args, **kwargs)
[Wed Apr 24 15:01:27.394675 2019] [wsgi:error] [pid 11940] [remote 162.158.155.116:47952]   File "/var/www/ExGen/ExGenApp/app/routes.py", line 194, in modules
[Wed Apr 24 15:01:27.394679 2019] [wsgi:error] [pid 11940] [remote 162.158.155.116:47952]     database.delete_one_student_from_module(session['studentid'], module_id)
[Wed Apr 24 15:01:27.394682 2019] [wsgi:error] [pid 11940] [remote 162.158.155.116:47952] UnboundLocalError: local variable 'module_id' referenced before assignment
[Wed Apr 24 15:04:58.491198 2019] [wsgi:error] [pid 12228] [remote 162.158.155.116:54204] [2019-04-24 15:04:58,489] ERROR in app: Exception on /modules/ [POST]
[Wed Apr 24 15:04:58.491230 2019] [wsgi:error] [pid 12228] [remote 162.158.155.116:54204] Traceback (most recent call last):
[Wed Apr 24 15:04:58.491233 2019] [wsgi:error] [pid 12228] [remote 162.158.155.116:54204]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 2292, in wsgi_app
[Wed Apr 24 15:04:58.491237 2019] [wsgi:error] [pid 12228] [remote 162.158.155.116:54204]     response = self.full_dispatch_request()
[Wed Apr 24 15:04:58.491240 2019] [wsgi:error] [pid 12228] [remote 162.158.155.116:54204]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1815, in full_dispatch_request
[Wed Apr 24 15:04:58.491243 2019] [wsgi:error] [pid 12228] [remote 162.158.155.116:54204]     rv = self.handle_user_exception(e)
[Wed Apr 24 15:04:58.491245 2019] [wsgi:error] [pid 12228] [remote 162.158.155.116:54204]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1718, in handle_user_exception
[Wed Apr 24 15:04:58.491248 2019] [wsgi:error] [pid 12228] [remote 162.158.155.116:54204]     reraise(exc_type, exc_value, tb)
[Wed Apr 24 15:04:58.491250 2019] [wsgi:error] [pid 12228] [remote 162.158.155.116:54204]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1813, in full_dispatch_request
[Wed Apr 24 15:04:58.491253 2019] [wsgi:error] [pid 12228] [remote 162.158.155.116:54204]     rv = self.dispatch_request()
[Wed Apr 24 15:04:58.491264 2019] [wsgi:error] [pid 12228] [remote 162.158.155.116:54204]   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1799, in dispatch_request
[Wed Apr 24 15:04:58.491266 2019] [wsgi:error] [pid 12228] [remote 162.158.155.116:54204]     return self.view_functions[rule.endpoint](**req.view_args)
[Wed Apr 24 15:04:58.491268 2019] [wsgi:error] [pid 12228] [remote 162.158.155.116:54204]   File "/var/www/ExGen/ExGenApp/app/routes.py", line 35, in wrap
[Wed Apr 24 15:04:58.491271 2019] [wsgi:error] [pid 12228] [remote 162.158.155.116:54204]     return f(*args, **kwargs)
[Wed Apr 24 15:04:58.491273 2019] [wsgi:error] [pid 12228] [remote 162.158.155.116:54204]   File "/var/www/ExGen/ExGenApp/app/routes.py", line 194, in modules
[Wed Apr 24 15:04:58.491275 2019] [wsgi:error] [pid 12228] [remote 162.158.155.116:54204]     database.delete_one_student_from_module(session['studentid'], module_id_delete)
[Wed Apr 24 15:04:58.491277 2019] [wsgi:error] [pid 12228] [remote 162.158.155.116:54204]   File "/var/www/ExGen/ExGenApp/app/db/database.py", line 219, in delete_one_student_from_module
[Wed Apr 24 15:04:58.491280 2019] [wsgi:error] [pid 12228] [remote 162.158.155.116:54204]     db_session.delete(student)
[Wed Apr 24 15:04:58.491282 2019] [wsgi:error] [pid 12228] [remote 162.158.155.116:54204]   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/scoping.py", line 157, in do
[Wed Apr 24 15:04:58.491284 2019] [wsgi:error] [pid 12228] [remote 162.158.155.116:54204]     return getattr(self.registry(), name)(*args, **kwargs)
[Wed Apr 24 15:04:58.491287 2019] [wsgi:error] [pid 12228] [remote 162.158.155.116:54204]   File "/usr/local/lib/python2.7/dist-packages/sqlalchemy/orm/session.py", line 1759, in delete
[Wed Apr 24 15:04:58.491289 2019] [wsgi:error] [pid 12228] [remote 162.158.155.116:54204]     raise exc.UnmappedInstanceError(instance)
[Wed Apr 24 15:04:58.491291 2019] [wsgi:error] [pid 12228] [remote 162.158.155.116:54204] UnmappedInstanceError: Class '__builtin__.NoneType' is not mapped
